// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdoqzTUNKIYZPvTSpZWQsYkunw856MX4I',
    appId: '1:407669310646:web:0d3399076fda2183329217',
    messagingSenderId: '407669310646',
    projectId: 'employeecard-8b901',
    authDomain: 'employeecard-8b901.firebaseapp.com',
    storageBucket: 'employeecard-8b901.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaMjH03zAuqPhLQCFHhJW4JI6kNAn0_rY',
    appId: '1:407669310646:android:f3faa6c94a39399d329217',
    messagingSenderId: '407669310646',
    projectId: 'employeecard-8b901',
    storageBucket: 'employeecard-8b901.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdoqzTUNKIYZPvTSpZWQsYkunw856MX4I',
    appId: '1:407669310646:web:5666111b38b29ed4329217',
    messagingSenderId: '407669310646',
    projectId: 'employeecard-8b901',
    authDomain: 'employeecard-8b901.firebaseapp.com',
    storageBucket: 'employeecard-8b901.appspot.com',
  );
}
